// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCumZKRH4bMRfuguOCnSHGidxI3UGkY244',
    appId: '1:662546318811:web:7e97dd96b7f6e804c953fe',
    messagingSenderId: '662546318811',
    projectId: 'sample-cf991',
    authDomain: 'sample-cf991.firebaseapp.com',
    databaseURL: 'https://sample-cf991-default-rtdb.firebaseio.com',
    storageBucket: 'sample-cf991.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28sX0FJlxzciWr5WTq9qpyeHWBrb34UM',
    appId: '1:662546318811:android:e9b7673fe484cf13c953fe',
    messagingSenderId: '662546318811',
    projectId: 'sample-cf991',
    databaseURL: 'https://sample-cf991-default-rtdb.firebaseio.com',
    storageBucket: 'sample-cf991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWQRagIRneXvqtCt-4kZKWM_Whn0IuZ8E',
    appId: '1:662546318811:ios:4be26f79d9d4fc25c953fe',
    messagingSenderId: '662546318811',
    projectId: 'sample-cf991',
    databaseURL: 'https://sample-cf991-default-rtdb.firebaseio.com',
    storageBucket: 'sample-cf991.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWQRagIRneXvqtCt-4kZKWM_Whn0IuZ8E',
    appId: '1:662546318811:ios:4be26f79d9d4fc25c953fe',
    messagingSenderId: '662546318811',
    projectId: 'sample-cf991',
    databaseURL: 'https://sample-cf991-default-rtdb.firebaseio.com',
    storageBucket: 'sample-cf991.appspot.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCumZKRH4bMRfuguOCnSHGidxI3UGkY244',
    appId: '1:662546318811:web:7dcb3e65e2edf797c953fe',
    messagingSenderId: '662546318811',
    projectId: 'sample-cf991',
    authDomain: 'sample-cf991.firebaseapp.com',
    databaseURL: 'https://sample-cf991-default-rtdb.firebaseio.com',
    storageBucket: 'sample-cf991.appspot.com',
  );

}